version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
      - pgvector
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./my-next-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./my-next-app:/src
      - /src/node_modules
      - /src/.next
    depends_on:
      - backend
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: always

  pgvector:
    image: ankane/pgvector:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=example_db
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d  # Add this line
    networks:
      - app-network
    restart: always

volumes:
  mongodb_data:
  pgvector_data:

networks:
  app-network:
    driver: bridge