version: '3.8'

services:
  postgres_pgvector:
    image: postgres:14
    container_name: postgres_pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgvector_data:/var/lib/postgresql/data
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  pgvector_data:
